INSERT INTO public.location (city, county)
VALUES ('Bucharest', 'Bucureşti'),
       ('Cluj-Napoca', 'Cluj'),
       ('Timişoara', 'Timiş'),
       ('Braşov', 'Braşov'),
       ('Iaşi', 'Iaşi'),
       ('Constanţa', 'Constanţa'),
       ('Craiova', 'Dolj'),
       ('Galaţi', 'Galaţi'),
       ('Ploieşti', 'Prahova'),
       ('Oradea', 'Bihor'),
       ('Brăila', 'Brăila'),
       ('Arad', 'Arad'),
       ('Piteşti', 'Argeş'),
       ('Sibiu', 'Sibiu'),
       ('Bacău', 'Bacău'),
       ('Târgu-Mureş', 'Mureş'),
       ('Baia Mare', 'Maramureş'),
       ('Buzău', 'Buzău'),
       ('Botoşani', 'Botoşani'),
       ('Satu Mare', 'Satu Mare'),
       ('Râmnicu Vâlcea', 'Vâlcea'),
       ('Drobeta-Turnu Severin', 'Mehedinţi'),
       ('Suceava', 'Suceava'),
       ('Piatra Neamţ', 'Neamţ'),
       ('Reşiţa', 'Caraş-Severin'),
       ('Târgu Jiu', 'Gorj'),
       ('Târgovişte', 'Dâmboviţa'),
       ('Focşani', 'Vrancea'),
       ('Bistriţa', 'Bistriţa-Năsăud'),
       ('Tulcea', 'Tulcea'),
       ('Slatina', 'Olt'),
       ('Călăraşi', 'Călăraşi'),
       ('Alba Iulia', 'Alba'),
       ('Vaslui', 'Vaslui'),
       ('Giurgiu', 'Giurgiu'),
       ('Deva', 'Hunedoara'),
       ('Hunedoara', 'Hunedoara'),
       ('Zalău', 'Sălaj'),
       ('Sfântu-Gheorghe', 'Covasna'),
       ('Bârlad', 'Vaslui'),
       ('Popeşti-Leordeni', 'Ilfov'),
       ('Roman', 'Neamţ'),
       ('Turda', 'Cluj'),
       ('Voluntari', 'Bucureşti'),
       ('Media', 'Sibiu'),
       ('Slobozia', 'Ialomiţa'),
       ('Alexandria', 'Teleorman'),
       ('Miercurea-Ciuc', 'Harghita'),
       ('Lugoj', 'Timiş'),
       ('Bragadiru', 'Ilfov'),
       ('Medgidia', 'Constanţa'),
       ('Oneşti', 'Bacău'),
       ('Sighetu Marmaţiei', 'Maramureş'),
       ('Petroşani', 'Hunedoara'),
       ('Mangalia', 'Constanţa'),
       ('Tecuci', 'Galaţi'),
       ('Năvodari', 'Constanţa'),
       ('Odorheiu Secuiesc', 'Harghita'),
       ('Râmnicu Sărat', 'Buzău'),
       ('Paşcani', 'Iaşi'),
       ('Dej', 'Cluj'),
       ('Reghin', 'Mureş'),
       ('Câmpina', 'Prahova'),
       ('Pantelimon', 'Ilfov'),
       ('Mioveni', 'Argeş'),
       ('Câmpulung', 'Argeş'),
       ('Caracal', 'Olt'),
       ('Săcele', 'Braşov'),
       ('Făgăraş', 'Braşov'),
       ('Feteşti', 'Ialomiţa'),
       ('Sighişoara', 'Mureş'),
       ('Borşa', 'Maramureş'),
       ('Roşiori de Vede', 'Teleorman'),
       ('Curtea de Argeş', 'Argeş'),
       ('Sebeş', 'Alba'),
       ('Huşi', 'Vaslui'),
       ('Fălticeni', 'Suceava'),
       ('Olteniţa', 'Călăraşi'),
       ('Turnu Măgurele', 'Teleorman'),
       ('Caransebeş', 'Caraş-Severin'),
       ('Dorohoi', 'Botoşani'),
       ('Rădăuţi', 'Suceava'),
       ('Vulcan', 'Hunedoara'),
       ('Zărneşti', 'Braşov'),
       ('Lupeni', 'Hunedoara'),
       ('Aiud', 'Alba'),
       ('Petrila', 'Hunedoara'),
       ('Cisnădie', 'Sibiu'),
       ('Câmpia Turzii', 'Cluj'),
       ('Buftea', 'Ilfov'),
       ('Târnăveni', 'Mureş'),
       ('Moineşti', 'Bacău'),
       ('Otopeni', 'Ilfov'),
       ('Codlea', 'Braşov'),
       ('Cugir', 'Alba'),
       ('Carei', 'Satu Mare'),
       ('Gherla', 'Cluj'),
       ('Scobinţi', 'Iaşi'),
       ('Blaj', 'Alba'),
       ('Floreşti', 'Cluj'),
       ('Comăneşti', 'Bacău'),
       ('Motru', 'Gorj'),
       ('Târgu Neamţ', 'Neamţ'),
       ('Moreni', 'Dâmboviţa'),
       ('Toflea', 'Galaţi'),
       ('Târgu Secuiesc', 'Covasna'),
       ('Gheorgheni', 'Harghita'),
       ('Orăştie', 'Hunedoara'),
       ('Balş', 'Olt'),
       ('Băicoi', 'Prahova'),
       ('Drăgăşani', 'Vâlcea'),
       ('Salonta', 'Bihor'),
       ('Băileşti', 'Dolj'),
       ('Calafat', 'Dolj'),
       ('Filiaşi', 'Dolj'),
       ('Câmpulung Moldovenesc', 'Suceava'),
       ('Corabia', 'Olt'),
       ('Adjud', 'Vrancea'),
       ('Breaza', 'Prahova'),
       ('Râşnov', 'Braşov'),
       ('Bocşa', 'Caraş-Severin'),
       ('Marghita', 'Bihor'),
       ('Baia-Sprie', 'Maramureş'),
       ('Vişeu de Sus', 'Maramureş'),
       ('Luduş', 'Mureş'),
       ('Urziceni', 'Ialomiţa'),
       ('Vicovu de Sus', 'Suceava'),
       ('Chitila', 'Ilfov'),
       ('Negreşti-Oaş', 'Satu Mare'),
       ('Buhuşi', 'Bacău'),
       ('Brad', 'Hunedoara'),
       ('Vatra Dornei', 'Suceava'),
       ('Măgurele', 'Ilfov'),
       ('Mizil', 'Prahova'),
       ('Pucioasa', 'Dâmboviţa'),
       ('Zimnicea', 'Teleorman'),
       ('Ovidiu', 'Constanţa'),
       ('Topliţa', 'Harghita'),
       ('Gura Humorului', 'Suceava'),
       ('Jimbolia', 'Timiş'),
       ('Găeşti', 'Dâmboviţa'),
       ('Dărmăneşti', 'Bacău'),
       ('Ocna Mureş', 'Alba'),
       ('Bolintin Vale', 'Giurgiu'),
       ('Avrig', 'Sibiu'),
       ('Pecica', 'Arad'),
       ('Simeria', 'Hunedoara'),
       ('Sântana', 'Arad'),
       ('Valu lui Traian', 'Constanţa'),
       ('Moldova Nouă', 'Caraş-Severin'),
       ('Cumpăna', 'Constanţa'),
       ('Sânnicolau Mare', 'Timiş'),
       ('Jilava', 'Ilfov'),
       ('Dăbuleni', 'Dolj'),
       ('Vălenii de Munte', 'Prahova'),
       ('Comarnic', 'Prahova'),
       ('Darabani', 'Botoşani'),
       ('Rovinari', 'Gorj'),
       ('Scorniceşti', 'Olt'),
       ('Târgu Lăpuş', 'Maramureş'),
       ('Matca', 'Galaţi'),
       ('Săcueni', 'Bihor'),
       ('Videle', 'Teleorman'),
       ('Oraviţa', 'Caraş-Severin'),
       ('Mărăşeşti', 'Vrancea'),
       ('Târgu Ocna', 'Bacău'),
       ('Călan', 'Hunedoara'),
       ('Beclean', 'Bistriţa-Năsăud'),
       ('Boldeşti-Scăeni', 'Prahova'),
       ('Dolhasca', 'Suceava'),
       ('Sângeorz-Băi', 'Bistriţa-Năsăud'),
       ('Hârlău', 'Iaşi'),
       ('Drăgăneşti-Olt', 'Olt'),
       ('Cristuru Secuiesc', 'Harghita'),
       ('Poiana Mare', 'Dolj'),
       ('Beiuş', 'Bihor'),
       ('Flămânzi', 'Botoşani'),
       ('Urlaţi', 'Prahova'),
       ('Oţelu Roşu', 'Caraş-Severin'),
       ('Strehaia', 'Mehedinţi'),
       ('Târgu Frumos', 'Iaşi'),
       ('Orşova', 'Mehedinţi'),
       ('Sinaia', 'Prahova'),
       ('Jibou', 'Sălaj'),
       ('Sovata', 'Mureş'),
       ('Costeşti', 'Argeş'),
       ('Ianca', 'Brăila'),
       ('Lipova', 'Arad'),
       ('Topoloveni', 'Argeş'),
       ('Murfatlar', 'Constanţa'),
       ('Năsăud', 'Bistriţa-Năsăud'),
       ('Nehoiu', 'Buzău'),
       ('Pechea', 'Galaţi'),
       ('Covasna', 'Covasna'),
       ('Poienile de sub Munte', 'Maramureş'),
       ('Aleşd', 'Bihor'),
       ('Valea lui Mihai', 'Bihor'),
       ('Haţeg', 'Hunedoara'),
       ('Titu', 'Dâmboviţa'),
       ('Liteni', 'Suceava'),
       ('Podu Iloaiei', 'Iaşi'),
       ('Salcea', 'Suceava'),
       ('Odobeşti', 'Vrancea'),
       ('Huedin', 'Cluj'),
       ('Ineu', 'Arad'),
       ('Babadag', 'Tulcea'),
       ('Cajvana', 'Suceava'),
       ('Seini', 'Maramureş'),
       ('Bumbeşti-Jiu', 'Gorj'),
       ('Buşteni', 'Prahova'),
       ('Sângeorgiu de Mureş', 'Mureş'),
       ('Agnita', 'Sibiu'),
       ('Săbăoani', 'Neamţ'),
       ('Iernut', 'Mureş'),
       ('Baraolt', 'Covasna'),
       ('Tăşnad', 'Satu Mare'),
       ('Bicaz', 'Neamţ'),
       ('Roznov', 'Neamţ'),
       ('Tăuţii Măgheruş', 'Maramureş'),
       ('Băbeni', 'Vâlcea'),
       ('Negreşti', 'Vaslui'),
       ('Recaş', 'Timiş'),
       ('Întorsura Buzăului', 'Covasna'),
       ('Măcin', 'Tulcea'),
       ('Tomeşti', 'Iaşi'),
       ('Techirghiol', 'Constanţa'),
       ('Târgu Cărbuneşti', 'Gorj'),
       ('Roşu', 'Bucureşti'),
       ('Chişineu Criş', 'Arad'),
       ('Borcea', 'Călăraşi'),
       ('Siret', 'Suceava'),
       ('Mihăileşti', 'Giurgiu'),
       ('Domneşti', 'Ilfov'),
       ('Prim Decembrie', 'Ilfov'),
       ('Budeşti', 'Călăraşi'),
       ('Vlăhiţa', 'Harghita'),
       ('Câmpeni', 'Alba'),
       ('Mogoşoaia', 'Ilfov'),
       ('Călimăneşti', 'Vâlcea'),
       ('Fieni', 'Dâmboviţa'),
       ('Modelu', 'Călăraşi'),
       ('Dumbrăviţa', 'Timiş'),
       ('Anina', 'Caraş-Severin'),
       ('Chirnogi', 'Călăraşi'),
       ('Curtici', 'Arad'),
       ('Nădlac', 'Arad'),
       ('Dumbrăveni', 'Sibiu'),
       ('Segarcea', 'Dolj'),
       ('Amara', 'Ialomiţa'),
       ('Brăneşti', 'Ilfov'),
       ('Pătârlagele', 'Buzău'),
       ('Pogoanele', 'Buzău'),
       ('Ulmeni', 'Maramureş'),
       ('Turceni', 'Gorj'),
       ('Cehu Silvaniei', 'Sălaj'),
       ('Ghimbav', 'Braşov'),
       ('Murgeni', 'Vaslui'),
       ('Buziaş', 'Timiş'),
       ('Ungheni', 'Mureş'),
       ('Săveni', 'Botoşani'),
       ('Pâncota', 'Arad'),
       ('Sărmaşu', 'Mureş'),
       ('Răcari', 'Dâmboviţa'),
       ('Panciu', 'Vrancea'),
       ('Tălmaciu', 'Sibiu'),
       ('Fundulea', 'Călăraşi'),
       ('Livada', 'Satu Mare'),
       ('Făget', 'Timiş'),
       ('Teiuş', 'Alba'),
       ('Lehliu-Gară', 'Călăraşi'),
       ('Horezu', 'Vâlcea'),
       ('Dancu', 'Iaşi'),
       ('Piatra Olt', 'Olt'),
       ('Bujor', 'Galaţi'),
       ('Baloteşti', 'Ilfov'),
       ('Deta', 'Timiş'),
       ('Ardud', 'Satu Mare'),
       ('Lunca Cetăţuii', 'Iaşi'),
       ('Dragalina', 'Călăraşi'),
       ('Bălan', 'Harghita'),
       ('Roseţi', 'Călăraşi'),
       ('Cornetu', 'Ilfov'),
       ('Slănic', 'Prahova'),
       ('Sebiş', 'Arad'),
       ('Berceni', 'Ilfov'),
       ('Săvineşti', 'Neamţ'),
       ('Frasin', 'Suceava'),
       ('Gătaia', 'Timiş'),
       ('Potcoava', 'Olt'),
       ('Fundeni', 'Călăraşi'),
       ('Giroc', 'Timiş'),
       ('Curcani', 'Călăraşi'),
       ('Miercurea Nirajului', 'Mureş'),
       ('Glina', 'Ilfov'),
       ('Copşa Mică', 'Sibiu'),
       ('Sâncraiu de Mureş', 'Mureş'),
       ('Baia de Aramă', 'Mehedinţi'),
       ('Vânju-Mare', 'Mehedinţi'),
       ('Geoagiu', 'Hunedoara'),
       ('Dobroeşti', 'Ilfov'),
       ('Rupea', 'Braşov'),
       ('Abrud', 'Alba'),
       ('Isaccea', 'Tulcea'),
       ('Băile Herculane', 'Caraş-Severin'),
       ('Tunari', 'Ilfov'),
       ('Milişăuţi', 'Suceava'),
       ('Valea Lupului', 'Iaşi'),
       ('Cavnic', 'Maramureş'),
       ('Fierbinţi-Târg', 'Ilfov'),
       ('Ulmeni', 'Călăraşi'),
       ('Volovăţ', 'Suceava'),
       ('Săliştea de Sus', 'Maramureş'),
       ('Bălceşti', 'Vâlcea'),
       ('Agigea', 'Constanţa'),
       ('Berbeşti', 'Vâlcea'),
       ('Cernele', 'Dolj'),
       ('Bucov', 'Prahova'),
       ('Predeal', 'Braşov'),
       ('Cristeşti', 'Mureş'),
       ('Clinceni', 'Ilfov'),
       ('Başcov', 'Argeş'),
       ('Ghiroda', 'Timiş'),
       ('Doiceşti', 'Dâmboviţa'),
       ('Chiajna', 'Ilfov'),
       ('Azuga', 'Prahova'),
       ('Voitinel', 'Suceava'),
       ('Aninoasa', 'Hunedoara'),
       ('Bechet', 'Dolj'),
       ('Valea Mare-Podgoria', 'Argeş'),
       ('Floreşti', 'Giurgiu'),
       ('Victoria', 'Iaşi'),
       ('Bucecea', 'Botoşani'),
       ('Ciocăneşti', 'Călăraşi'),
       ('Cenad', 'Timiş'),
       ('Slănic-Moldova', 'Bacău'),
       ('Perişoru', 'Călăraşi'),
       ('Ungheni-Prut', 'Iaşi'),
       ('Pleaşa', 'Prahova'),
       ('Baia de Arieş', 'Alba'),
       ('Fundeni', 'Bucureşti'),
       ('Ciorogârla', 'Ilfov'),
       ('Miercurea Sibiului', 'Sibiu'),
       ('Radovanu', 'Călăraşi'),
       ('Sfântu Ilie', 'Suceava'),
       ('Gălbinaşi', 'Călăraşi'),
       ('Ipoteşti', 'Suceava'),
       ('Dor Mărunt', 'Călăraşi'),
       ('Blejoiu', 'Prahova'),
       ('Pârcovaci', 'Iaşi'),
       ('Făurei', 'Brăila'),
       ('Vasilaţi', 'Călăraşi'),
       ('Mânăstirea', 'Călăraşi'),
       ('Ocna Sibiului', 'Sibiu'),
       ('Cornu de Jos', 'Prahova'),
       ('Mărgineni', 'Bacău'),
       ('Sântana de Mureş', 'Mureş'),
       ('Adjudeni', 'Neamţ'),
       ('Chiselet', 'Călăraşi'),
       ('Ocnele Mari', 'Vâlcea'),
       ('Căpăţâneşti', 'Buzău'),
       ('Căzăneşti', 'Ialomiţa'),
       ('Mărăcineni', 'Argeş'),
       ('Bărcăneşti', 'Prahova'),
       ('Ploeştiori', 'Prahova'),
       ('Dragomireşti', 'Maramureş'),
       ('Malu Spart', 'Giurgiu'),
       ('Brăneşti', 'Dâmboviţa'),
       ('Cernica', 'Ilfov'),
       ('Copăcenii de Jos', 'Giurgiu'),
       ('Tânganu', 'Călăraşi'),
       ('Băneşti', 'Prahova'),
       ('Tămăşeni', 'Neamţ'),
       ('Dărăşti-Ilfov', 'Ilfov'),
       ('Iazu', 'Dâmboviţa'),
       ('Tătărani', 'Prahova'),
       ('Goranu', 'Vâlcea'),
       ('Mărăcineni', 'Buzău'),
       ('Braniştea', 'Dâmboviţa'),
       ('Buciumeni', 'Ilfov'),
       ('Fântânele', 'Dâmboviţa'),
       ('Frumuşani', 'Călăraşi'),
       ('Bereşti-Târg', 'Galaţi'),
       ('Bălăceanca', 'Ilfov'),
       ('Două Mai', 'Constanţa'),
       ('Căţelu', 'Ilfov'),
       ('Palanca', 'Giurgiu'),
       ('Stancea', 'Călăraşi'),
       ('Holboca', 'Iaşi'),
       ('Dragomireşti-Deal', 'Ilfov'),
       ('Nana', 'Călăraşi'),
       ('Rasova', 'Călăraşi'),
       ('Gârcina', 'Neamţ'),
       ('Filipeştii de Târg', 'Prahova'),
       ('Decindeni', 'Dâmboviţa'),
       ('Teiş', 'Dâmboviţa'),
       ('Corbeanca', 'Ilfov'),
       ('Viforâta', 'Dâmboviţa'),
       ('Băile Govora', 'Vâlcea'),
       ('Bogdan Vodă', 'Maramureş'),
       ('Solca', 'Suceava'),
       ('Ciurea', 'Iaşi'),
       ('Răzvani', 'Călăraşi'),
       ('Aninoasa', 'Dâmboviţa'),
       ('Cojasca', 'Dâmboviţa'),
       ('Vaşcău', 'Bihor'),
       ('Luna de Sus', 'Cluj'),
       ('Maxut', 'Iaşi'),
       ('Valea Roşie', 'Călăraşi'),
       ('Dârvari', 'Ilfov'),
       ('Malu Alb', 'Galaţi'),
       ('Crivăţ', 'Călăraşi'),
       ('Miroslava', 'Iaşi'),
       ('Tonea', 'Călăraşi'),
       ('Unirea', 'Călăraşi'),
       ('Cuza Vodă', 'Călăraşi'),
       ('Nucet', 'Bihor'),
       ('Lipăneşti', 'Prahova'),
       ('Urleta', 'Prahova'),
       ('Grădiştea', 'Călăraşi'),
       ('Dragomireşti', 'Dâmboviţa'),
       ('Independenţa', 'Călăraşi'),
       ('Asău', 'Bacău'),
       ('Stoeneşti', 'Giurgiu'),
       ('Nazna', 'Mureş'),
       ('Valea Râmnicului', 'Buzău'),
       ('Tamaşi', 'Ilfov'),
       ('Remuş', 'Giurgiu'),
       ('Săsar', 'Maramureş'),
       ('Râncăciov', 'Dâmboviţa'),
       ('Potoceni', 'Buzău'),
       ('Cornetu', 'Vrancea'),
       ('Româneşti', 'Prahova'),
       ('Lipia', 'Buzău'),
       ('Argeşelu', 'Argeş'),
       ('Jegălia', 'Călăraşi'),
       ('Sohatu', 'Călăraşi'),
       ('Căscioarele', 'Călăraşi'),
       ('Mislea', 'Prahova'),
       ('Colibaşi', 'Argeş'),
       ('Olteni', 'Ilfov'),
       ('Lehliu', 'Călăraşi'),
       ('Măneuţi', 'Suceava'),
       ('Sântion', 'Bihor'),
       ('Dorolţ', 'Satu Mare'),
       ('Dudu', 'Ilfov'),
       ('Racoviţa', 'Argeş'),
       ('Plătăreşti', 'Călăraşi'),
       ('Bogata', 'Mureş'),
       ('Luica', 'Călăraşi'),
       ('Săruleşti-Gară', 'Călăraşi'),
       ('Băile Tuşnad', 'Harghita'),
       ('Ostratu', 'Ilfov'),
       ('Lazu', 'Constanţa'),
       ('Dorobanţu', 'Călăraşi'),
       ('Islaz', 'Ilfov'),
       ('Plopeni', 'Prahova'),
       ('Dragomireşti-Vale', 'Ilfov'),
       ('Lunga', 'Covasna'),
       ('Vlad Ţepeş', 'Călăraşi'),
       ('Sânleani', 'Arad'),
       ('Lieşti', 'Vrancea'),
       ('Săteni', 'Dâmboviţa'),
       ('Moţăeni', 'Dâmboviţa'),
       ('Săftica', 'Ilfov'),
       ('Valea Argovei', 'Călăraşi'),
       ('Bucovăţ', 'Dolj'),
       ('Mitreni', 'Călăraşi'),
       ('Dedrad', 'Mureş'),
       ('Valea Vişeului', 'Maramureş'),
       ('Adjudu Vechi', 'Vrancea'),
       ('Corlăteşti', 'Prahova'),
       ('Breazu', 'Iaşi'),
       ('Nicolae Bălcescu', 'Călăraşi'),
       ('Aghireş', 'Sălaj'),
       ('Piteasca', 'Ilfov'),
       ('Gâldău', 'Călăraşi'),
       ('Radu Vodă', 'Călăraşi'),
       ('Ighişu Nou', 'Sibiu'),
       ('Pasărea', 'Ilfov'),
       ('Odăile', 'Ilfov'),
       ('Progresu', 'Călăraşi'),
       ('Vânători', 'Iaşi'),
       ('Teliucu Inferior', 'Hunedoara'),
       ('Cristur', 'Hunedoara'),
       ('Feteşti', 'Iaşi'),
       ('Dumbrava', 'Iaşi'),
       ('Drajna Nouă', 'Călăraşi'),
       ('Goruni', 'Iaşi'),
       ('Hăghiac', 'Bacău'),
       ('Nicolae Bălcescu', 'Călăraşi'),
       ('Dorobanţu', 'Călăraşi'),
       ('Ulmi', 'Dâmboviţa'),
       ('Vâlcelele', 'Călăraşi'),
       ('Ceacu', 'Călăraşi'),
       ('Uiasca', 'Argeş'),
       ('Dâmbovicioara', 'Dâmboviţa'),
       ('Chiţorani', 'Prahova'),
       ('Sălcioara', 'Ialomiţa'),
       ('Izvoarele', 'Iaşi'),
       ('Cătina', 'Prahova'),
       ('Rasa', 'Călăraşi'),
       ('Traian', 'Neamţ'),
       ('Căldăraru', 'Ilfov'),
       ('Budeasa Mare', 'Argeş'),
       ('Aprozi', 'Călăraşi'),
       ('Straja', 'Bacău'),
       ('Peştişu Mare', 'Hunedoara'),
       ('Valea Mare-Pravăţ', 'Argeş'),
       ('Ocina de Sus', 'Prahova'),
       ('Valea Mare', 'Vâlcea'),
       ('Chicerea', 'Iaşi'),
       ('Negoeşti', 'Călăraşi'),
       ('Belciugatele', 'Călăraşi'),
       ('Bughea de Jos', 'Prahova'),
       ('Scobâlţeni', 'Iaşi'),
       ('Tămădău Mare', 'Călăraşi'),
       ('Vălureni', 'Mureş'),
       ('Alexandru Odobescu', 'Călăraşi'),
       ('Cornu de Sus', 'Prahova'),
       ('Sultana', 'Călăraşi'),
       ('Glâmbocu', 'Argeş'),
       ('Curteni', 'Mureş'),
       ('Bobolia', 'Prahova'),
       ('Sălcuţa', 'Dâmboviţa'),
       ('Valea Stânii', 'Argeş'),
       ('Poiana Copăceni', 'Prahova'),
       ('Vărăşti', 'Călăraşi'),
       ('Ileana', 'Călăraşi');
