### Sign Up
POST {{host}}/auth/signUp
Content-Type: application/json

{
  "email": "user@m.com",
  "password": "pass",
  "firstName": "user",
  "lastName": "teddy",
  "phoneNumber": "07223",
  "birthDate": "2000-02-05"
}


### Sign In
POST {{host}}/auth/signIn
Content-Type: application/json

{
  "email": "admin@m.com",
  "password": "pass123"
}

### Sign Out
POST {{host}}/auth/signOut
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJSaWRlU2hhcmUiLCJzdWIiOiJhZG1pbkBtLmNvbSIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzE3NTU5MzQ5LCJleHAiOjE3MTc1NjAyNDl9.CoU5dFe44D5CEfKhYTmwwLV6ztxI79U00fBUCY24RW3QFo1oDRauBcTy8-BKmesu5bJz-O6UjzvaUyFErI4Zh1RyiOQoi65Hsad1_kkK-RWBqgLyF78yXVRvNP8GT4m6sC_jC4yzOTKyZ9bFKdZ58xybHWMIcyrNF8zdCjLgAGbPbYWFT6fjZXDT1uOnPIJzEJIhPdvv0yKUgwNwsMNyemS6niZNcaS8DQXIw6-ASRRwHEF3-0-bwpgP7hvIw8XaFgs-me5hFPBpz2MmGGzyraRXNHDkZr969UOKimIT7F311m_mxB0QVv4yToBgrjKw2AEuNc2UWbljUAkJYn_8pntBUPJybmpIozaQPpcsqAv-l4-WDnHyko74gzQJshbwp8gwdGI-m6lAEE06-5Ud3aUw1HVzSO6uPf8dvp-wTM_lmz9A7FixQ8m_cZzjNL7sXaGXltRgxac4sNL9inZ41QD4sgknHCoJRvy7oidXKTlaiUvwiRUFCbKdONfGeVz4KAFBMnzDcAdodaLNlamqOI2t3mpXfVJ_nkJfFNYzga-XgQ8Uq6AuwgH7qe3heWjrWzQhz640zwX8TLHaS-81GtNa-8iVg-bMkTnIWyRL8Q9ZNo7H1V7062mzwJ-jshl_AMB1NTQm-9H039jJvVjO3HKjldsUvvNLQKZlnZeK3ag

{
  "refreshToken": "ot9op8urf4supa6rmou66drucjsjslqh6krk6bcjc3idafdtd13097unhndbugobf37cccg12avpe1ipr1a81et665rm9dt98to9nriuk8rerk4bnb6j12v3rppb5vr7"
}
